"""
DJANGO MIGRATION FILE - Database Schema Changes

This is an AUTO-GENERATED file that Django creates when you run:
python manage.py makemigrations

WHAT THIS MIGRATION DOES:
This is the INITIAL migration for the a_users app. It creates the Profile table
in the database with all the necessary columns and relationships.

MIGRATION WORKFLOW:
1. You change models.py (add/modify/delete fields)
2. Run 'python manage.py makemigrations' (creates this file)
3. Run 'python manage.py migrate' (applies changes to database)

IMPORTANT NOTES:
- NEVER edit this file manually unless you know what you're doing
- These files are version control for your database
- Each migration has a unique number (0001, 0002, etc.)
- Django tracks which migrations have been applied
"""

# Generated by Django 5.2.4 on 2025-09-13 08:31

import django.db.models.deletion  # For foreign key relationships
from django.conf import settings   # For referencing AUTH_USER_MODEL
from django.db import migrations, models  # Django's migration framework


class Migration(migrations.Migration):
    """
    INITIAL MIGRATION - Creates the Profile model table
    
    This migration creates the database table for storing user profiles.
    It's called 'initial' because it's the first migration for this app.
    """

    initial = True  # Marks this as the first migration for the app

    # DEPENDENCIES - What must exist before this migration runs
    dependencies = [
        # Profile model has a foreign key to User, so User table must exist first
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # OPERATIONS - The actual database changes to make
    operations = [
        # CREATE TABLE - Creates the 'a_users_profile' table
        migrations.CreateModel(
            name='Profile',  # Model name (becomes 'a_users_profile' table)
            fields=[
                # PRIMARY KEY - Auto-incrementing ID field (required by Django)
                ('id', models.BigAutoField(
                    auto_created=True,    # Django creates this automatically
                    primary_key=True,     # This is the table's primary key
                    serialize=False,      # Don't include in serialized data
                    verbose_name='ID'     # Human-readable name
                )),
                
                # PROFILE IMAGE - File upload field for user avatars
                ('image', models.ImageField(
                    blank=True,           # Can be empty in forms
                    null=True,            # Can be NULL in database
                    upload_to='avatars/'  # Files saved to media/avatars/
                )),
                
                # DISPLAY NAME - Optional custom name (max 20 characters)
                ('displayname', models.CharField(
                    blank=True,      # Can be empty in forms
                    max_length=20,   # Maximum 20 characters
                    null=True        # Can be NULL in database
                )),
                
                # USER INFO/BIO - Optional text field for user biography
                ('info', models.TextField(
                    blank=True,  # Can be empty in forms
                    null=True    # Can be NULL in database
                )),
                
                # USER RELATIONSHIP - Links Profile to Django's User model
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,  # Delete profile if user is deleted
                    to=settings.AUTH_USER_MODEL  # Points to Django's User model
                )),
            ],
        ),
    ]

# WHAT HAPPENS WHEN THIS MIGRATION RUNS:
# 1. Django creates a table called 'a_users_profile'
# 2. Table gets columns: id, image, displayname, info, user_id
# 3. Creates foreign key constraint linking user_id to auth_user.id
# 4. Creates unique constraint ensuring one profile per user
# 5. Sets up indexes for efficient database queries
#
# REVERSE MIGRATION:
# If you need to undo this migration:
# python manage.py migrate a_users zero  # Removes all tables for this app
