"""
⚙️ SETTINGS.PY - The Control Panel of Your Django Project! ⚙️

Everything Django does is configured here - from database connections to security settings.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path  # Modern way to handle file paths (better than old 'os.path')

# 🏠 PROJECT ROOT DIRECTORY
# This finds where your project lives on your computer
# __file__ = this current file (settings.py)
# .resolve() = get the absolute path 
# .parent.parent = go up two levels (from a_core/settings.py to Drift/)
BASE_DIR = Path(__file__).resolve().parent.parent
# Result: /Projects/Drift/


# 🔐 SECURITY SETTINGS - Keep Your App Safe!
# ==========================================

# 🔑 SECRET KEY - Django's Master Password
# This is used for cryptographic signing (sessions, cookies, etc.)
# ⚠️  NEVER share this in production! Change it before going live!
SECRET_KEY = 'django-insecure-w(e2r1kh_k6o8d=cokm=e4v83f_g8rid9nfqa*of4*7(5&**0bhx'

# 🐛 DEBUG MODE - Shows detailed errors when things break
# True = Development (shows helpful error pages)
# False = Production (shows generic error pages)
DEBUG = True

# 🌐 ALLOWED HOSTS - Who can access your website
# List of domains/IPs that can serve your Django app
# ['*'] = Anyone can access (only safe during development!)
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']

# 🔧 DJANGO FRAMEWORK CONFIGURATION
# =================================

# 🌍 SITE ID - For Django's sites framework
# Useful when running multiple websites from one Django project
SITE_ID = 1

# 🛡️ AUTHENTICATION BACKENDS - How users log in
# Think of these as different "doors" users can enter through
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',            # Standard Django login (username/password)
    'allauth.account.auth_backends.AuthenticationBackend',  # Enhanced login (email, social, etc.)
)

# 📦 INSTALLED APPS - The Building Blocks of Your Project
# ======================================================
# Think of each app as a LEGO block that adds functionality

INSTALLED_APPS = [
    # 🏗️ DJANGO'S BUILT-IN APPS (The Foundation)
    'django.contrib.admin',        # 👨‍💼 Admin panel (like WordPress admin)
    'django.contrib.auth',         # 👤 User accounts and permissions
    'django.contrib.contenttypes', # 🏷️  Tracks what types of data you have
    'django.contrib.sessions',     # 🍪 Remembers users between page visits
    'django.contrib.messages',     # 💬 Success/error messages to users
    'django.contrib.staticfiles',  # 📁 CSS, JS, images handling
    'django.contrib.sites',        # 🌐 Multi-site support
    
    # 🔧 THIRD-PARTY APPS (Extra Superpowers)
    'django_cleanup.apps.CleanupConfig',  # 🧹 Automatically deletes old uploaded files
    'allauth',                            # 🚪 Advanced authentication system
    'allauth.account',                    # 📧 User accounts with email verification
    'allauth.socialaccount',              # 📱 Login with Google, Facebook, etc.
    'django_htmx',                        # ⚡ Makes pages feel like single-page apps
    
    # 🏠 YOUR CUSTOM APPS (Your Unique Features)
    'a_home',   # 🏡 Homepage functionality
    'a_users',  # 👥 User profiles and management
]

# 🔄 MIDDLEWARE - The Security Guards & Traffic Controllers
# ========================================================
# Middleware processes EVERY request before it reaches your views
# Think of them as security checkpoints at an airport

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # 🛡️  Adds security headers
    'django.contrib.sessions.middleware.SessionMiddleware',    # 🍪 Handles user sessions
    'django.middleware.common.CommonMiddleware',               # 🔧 Common functionality
    'django.middleware.csrf.CsrfViewMiddleware',               # 🛡️  Prevents cross-site attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 👤 Identifies users
    'django.contrib.messages.middleware.MessageMiddleware',    # 💬 Handles messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # 🛡️  Prevents clickjacking
    'allauth.account.middleware.AccountMiddleware',            # 🔐 Enhanced user management
    'django_htmx.middleware.HtmxMiddleware',                   # ⚡ HTMX functionality
]

# 🗺️ URL CONFIGURATION - The GPS System
# =====================================
# Tells Django where to look for URL patterns
ROOT_URLCONF = 'a_core.urls'  # Points to a_core/urls.py

# 🎨 TEMPLATES - The HTML Generators
# ==================================
# Configuration for how Django renders HTML pages

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',   # Template engine
        'DIRS': [ BASE_DIR / 'templates' ],                             # 📁 Where to find template files
        'APP_DIRS': True,                                               # 🔍 Also look for templates inside each app
        'OPTIONS': {
            'context_processors': [                                     # 🎯 Add extra data to every template
                'django.template.context_processors.request',           # Access to request object
                'django.contrib.auth.context_processors.auth',          # Access to user info
                'django.contrib.messages.context_processors.messages',  # Access to messages
            ],
        },
    },
]

# 🌐 WSGI APPLICATION - The Web Server Interface
# =============================================
# How your Django app communicates with web servers (Apache, Nginx, etc.)
WSGI_APPLICATION = 'a_core.wsgi.application'


# 💾 DATABASE CONFIGURATION - Where Your Data Lives
# =================================================

DATABASES = {
    'default': {  # Your main database
        'ENGINE': 'django.db.backends.sqlite3',  # 🏪 Database type (SQLite = simple file)
        'NAME': BASE_DIR / 'db.sqlite3',         # 📍 Database file location
    }
}

# 💡 OTHER DATABASE OPTIONS:
# PostgreSQL: 'django.db.backends.postgresql'
# MySQL: 'django.db.backends.mysql'
# Oracle: 'django.db.backends.oracle'


# 🔒 PASSWORD VALIDATION - Keep Passwords Strong
# =============================================
# Rules that passwords must follow

AUTH_PASSWORD_VALIDATORS = [
    {
        # 🚫 Password can't be too similar to user info (name, email, etc.)
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # 📏 Password must be at least 8 characters long
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # 🚫 Can't use common passwords like "password123"
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # 🚫 Password can't be entirely numeric
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 🌍 INTERNATIONALIZATION - Language & Location Settings
# ====================================================

LANGUAGE_CODE = 'en-us'  # 🇺🇸 Default language (English-US)
TIME_ZONE = 'UTC'        # 🕐 Time zone (Coordinated Universal Time)
USE_I18N = True          # 🌐 Enable internationalization (multiple languages)
USE_TZ = True            # ⏰ Enable timezone support


# 📁 STATIC FILES - CSS, JavaScript, Images
# =========================================
# Configuration for files that don't change (CSS, JS, logos, etc.)

STATIC_URL = 'static/'                      # 🔗 URL prefix for static files
STATICFILES_DIRS = [ BASE_DIR / 'static' ]  # 📁 Where Django looks for static files

# 📸 MEDIA FILES - User Uploads
# =============================
# Configuration for files users upload (profile pictures, documents, etc.)

MEDIA_URL = 'media/'                # 🔗 URL prefix for uploaded files
MEDIA_ROOT = BASE_DIR / 'media'     # 📁 Where uploaded files are stored

# 🏷️ DEFAULT PRIMARY KEY FIELD TYPE
# =================================
# How Django creates ID fields for database tables
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Uses big integers for IDs


# 🔐 AUTHENTICATION & USER MANAGEMENT SETTINGS
# ============================================

# 🎯 Where to redirect users after login/logout
LOGIN_REDIRECT_URL = '/'                              # After login: go to homepage
ACCOUNT_SIGNUP_REDIRECT_URL = '/profile/onboarding/'  # After signup: complete profile
LOGOUT_REDIRECT_URL = '/'                             # After logout: go to homepage

# 📧 EMAIL SETTINGS
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Print emails to console

# 🔐 ALLAUTH SETTINGS (Advanced Authentication)
ACCOUNT_LOGIN_METHODS = {'email', 'username'}  # Users can login with email OR username
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']  # Required signup fields
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Don't require email verification (for development)

# 💡 WHAT EACH SETTING MEANS:
# - LOGIN_REDIRECT_URL: "After someone logs in, where should they go?"
# - LOGOUT_REDIRECT_URL: "After someone logs out, where should they go?"
# - EMAIL_BACKEND: "How should we send emails?" (console = just print them)
# - ACCOUNT_LOGIN_METHODS: "How can users log in?" (email OR username)
# - ACCOUNT_EMAIL_VERIFICATION: "Do users need to verify their email?" (none = no)
